// import "./creational/Creator_method"
// import "./creational/Abstract_factory"
// import "./creational/Builder";
// import "./creational/Prototype"
// import "./creational/Singletone";
// import "./structural/Adapter";
// import "./structural/Bridge"
// import "./structural/Composite";
// import "./structural/Decorator"
// import "./structural/Facade";
// import "./structural/Flyweight";
// import "./structural/Proxy";
// import "./behavioral/ChainOfResponsibility";
// import "./behavioral/Command";
// import "./behavioral/Iterator";
// import "./behavioral/Mediator";
// import "./behavioral/Memento";
// import "./behavioral/Observer";
import "./behavioral/State";
